config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'welcome/index'
 
  resources :books
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
	validates :title, presence: true,
                    length: { minimum: 5 }  
  mount_uploader :attachment, AttachmentUploader  
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :username,  :uniqueness => { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController	
	before_action :find_book, only: [:show,:edit,:update,:destroy,]
	before_action :authenticate_user!

	def index    
		if params[:search]
		  @books = Book.all.joins(:user).where("lower(title) LIKE ? or lower(text) LIKE ? or users.username LIKE ?", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%", "%#{params[:search].downcase}%") 	   
		else
			@books = Book.all.includes(:user) 
		end
		respond_to do |format|
		  format.html  # index.html.erb
		  format.js
		end
	end
	
	
	def new
		@book = Book.new
	end
  	
	def create
		@book = Book.new(book_params)
		@book.attachment = params[:book][:attachment]
		@book.user_id = current_user.id
		if @book.save
			redirect_to @book
		else
			render 'new'
		end
	end

	def edit		
		puts @book.user_id
		puts current_user.id
		if @book.user_id != current_user.id
			puts "Here"
			redirect_to books_path
		end
	end
  	
	def update
		if @book.update(book_params)
			redirect_to @book
		else
			render 'edit'
		end
	end
 
	def destroy
		@book.destroy
		redirect_to books_path	
	end

	def find_book
		@book= Book.find(params[:id])
	end

	private

	def book_params
		params.require(:book).permit(:title, :text, :attachment)
	end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_books.html.erb
<%if @books.present?%>
  <table>
    <tr>
      <br>
      <th>Title</th>
      <th>Text</th>
      <th>Date/Time</th>
      <th>Username</th>
      <th colspan="2"></th>
    </tr>    
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.text %></td>
        <td><%= book.created_at %></td>
        <td><%= book.user.try(:username) %></td>
        <td><%= link_to 'Show', book_path(book) %></td> 
        <% if book.user_id == current_user.id %>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Destroy', book_path(book),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
                <% end %>
         <% end %>       
      </tr>
    <% end %>
  </table>
<%end%>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |form| %>
 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.label :attachment  %><br>
    <%= form.file_field :attachment %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>
 <%= render 'form' %>
 <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<body>
  <br>
  <div class="id">
    <h1>Listing books</h1>
    <br>
      <%= link_to 'New book', new_book_path %>
      <%= form_tag @book_path, :method => 'get' ,remote:true do %>
    <p>  
    <br>
      <%= text_field_tag :search, params[:search], id: "search" %>
      <%= submit_tag "Search",id: "search_btn" %>
  </div>
  <% end %>
<br>
<br>
   <div class ="books">
      <%= render 'books' %>
   </div>
<br>
<br>
<% if user_signed_in? %>
  <li>
    <%= button_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path)  %>  
  </li>

<script type="text/javascript" src="somescript.js">
   $("#search_btn").click(function(evt){
     evt.preventDefault();
      $.ajax({
      type: "get",
      url: "books_path",
      data: $(this).serialize(),
      success: function(response) {
     }
   });
})
</script>
<% end %>
</body>

app/views/books/index.js.erb
$('.books').html("<%= escape_javascript render(:partial => 'books', :locals => { :c => @books }) %>");

app/views/books/new.html.erb
<h1>New book</h1>
 <%= render 'form' %>
 <%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
   <strong>Title:</strong>
   <%= @book.title %>
</p>
<p>
   <strong>Text:</strong>
   <%= @book.text %>
</p>
  <%=link_to "show pdf",@book.attachment.url %>
  <%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My login', controller: 'books' %>